DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS questions;

DROP INDEX IF EXISTS idx_email;
;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    country TEXT,
    level INTEGER DEFAULT 0,
    rank TEXT NOT NULL
);

INSERT INTO users (user, email, password, country, level, rank)
VALUES ('admin', 'admin@example.com', '1234', 've', 0, 'BEGINNER'),
VALUES ('john_doe', 'john@example.com', '12345', 'us', 10, 'BEGINNER'),
VALUES ('alice_w', 'alice@example.com', 'pass123', 'ca', 15, 'BEGINNER'),
VALUES ('bob_the_builder', 'bob@build.com', 'canwefixit', 'gb', 20, 'BEGINNER'),
VALUES ('lucy_queen', 'lucy@shine.org', 'crownme', 'es', 25, 'BEGINNER'),
VALUES ('nina_x', 'nina@nowhere.com', 'securepass', 'de', 5, 'BEGINNER');


CREATE TABLE preguntas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    answer TEXT NOT NULL,
    rank TEXT NOT NULL,
    rutaImagen TEXT
);

-- Preguntas de la categoria capitales
INSERT INTO preguntas (category, description, answer, rank) VALUES
('capitales', '¿Cuál es la capital de Afganistán?', 'Kabul', 'TOURIST'),
('capitales', '¿Cuál es la capital de Albania?', 'Tirana', 'NOMAD'),
('capitales', '¿Cuál es la capital de Alemania?', 'Berlín', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Andorra?', 'Andorra la Vieja', 'NOMAD'),
('capitales', '¿Cuál es la capital de Angola?', 'Luanda', 'NOMAD'),
('capitales', '¿Cuál es la capital de Arabia Saudita?', 'Riad', 'TOURIST'),
('capitales', '¿Cuál es la capital de Argentina?', 'Buenos Aires', 'TOURIST'),
('capitales', '¿Cuál es la capital de Armenia?', 'Ereván', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Australia?', 'Canberra', 'TOURIST'),
('capitales', '¿Cuál es la capital de Austria?', 'Viena', 'NOMAD'),
('capitales', '¿Cuál es la capital de Azerbaiyán?', 'Baku', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Bahrein?', 'Manama', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Bangladesh?', 'Dhaka', 'NOMAD'),
('capitales', '¿Cuál es la capital de Barbados?', 'Bridgetown', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Bielorrusia?', 'Minsk', 'NOMAD'),
('capitales', '¿Cuál es la capital de Bélgica?', 'Bruselas', 'TOURIST'),
('capitales', '¿Cuál es la capital de Belice?', 'Belmopán', 'NOMAD'),
('capitales', '¿Cuál es la capital de Benín?', 'Porto Novo', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Bhutan?', 'Thimphu', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Bosnia y Herzegovina?', 'Sarajevo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Botsuana?', 'Gaborone', 'NOMAD'),
('capitales', '¿Cuál es la capital de Brasil?', 'Brasilia', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Brunei?', 'Bandar Seri Begawan', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Bulgaria?', 'Sofía', 'NOMAD'),
('capitales', '¿Cuál es la capital de Burkina Faso?', 'Ouagadougou', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Burundi?', 'Gitega', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Cabo Verde?', 'Praia', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Camboya?', 'Phnom Penh', 'NOMAD'),
('capitales', '¿Cuál es la capital de Camerún?', 'Yaundé', 'NOMAD'),
('capitales', '¿Cuál es la capital de Canadá?', 'Ottawa', 'TOURIST'),
('capitales', '¿Cuál es la capital de Catar?', 'Doha', 'NOMAD'),
('capitales', '¿Cuál es la capital de Chile?', 'Santiago', 'TOURIST'),
('capitales', '¿Cuál es la capital de China?', 'Pekín', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Chipre?', 'Nicosia', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Ciudad del Vaticano?', 'Ciudad del Vaticano', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Colombia?', 'Bogotá', 'TOURIST'),
('capitales', '¿Cuál es la capital de Comoras?', 'Moroni', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Congo?', 'Brazzaville', 'NOMAD'),
('capitales', '¿Cuál es la capital de República Democrática del Congo?', 'Kinshasa', 'NOMAD'),
('capitales', '¿Cuál es la capital de Corea del Norte?', 'Pionyang', 'TOURIST'),
('capitales', '¿Cuál es la capital de Corea del Sur?', 'Seúl', 'TOURIST'),
('capitales', '¿Cuál es la capital de Costa de Marfil?', 'Yamusukro', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Costa Rica?', 'San José', 'NOMAD'),
('capitales', '¿Cuál es la capital de Croacia?', 'Zagreb', 'NOMAD'),
('capitales', '¿Cuál es la capital de Cuba?', 'La Habana', 'TOURIST'),
('capitales', '¿Cuál es la capital de Dinamarca?', 'Copenhague', 'NOMAD'),
('capitales', '¿Cuál es la capital de Dominica?', 'Roseau', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Ecuador?', 'Quito', 'NOMAD'),
('capitales', '¿Cuál es la capital de Egipto?', 'El Cairo', 'TOURIST'),
('capitales', '¿Cuál es la capital de El Salvador?', 'San Salvador', 'TOURIST'),
('capitales', '¿Cuál es la capital de Emiratos Árabes Unidos?', 'Abu Dhabi', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Eritrea?', 'Asmara', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Eslovaquia?', 'Bratislava', 'NOMAD'),
('capitales', '¿Cuál es la capital de Eslovenia?', 'Liubliana', 'NOMAD'),
('capitales', '¿Cuál es la capital de España?', 'Madrid', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Estados Unidos?', 'Washington D.C.', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Estonia?', 'Tallin', 'NOMAD'),
('capitales', '¿Cuál es la capital de Etiopía?', 'Adís Abeba', 'NOMAD'),
('capitales', '¿Cuál es la capital de Fiji?', 'Suva', 'Aprendiz'),
('capitales', '¿Cuál es la capital de Filipinas?', 'Manila', 'NOMAD'),
('capitales', '¿Cuál es la capital de Finlandia?', 'Helsinki', 'NOMAD'),
('capitales', '¿Cuál es la capital de Francia?', 'París', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Gabón?', 'Libreville', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Gambia?', 'Banjul', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Georgia?', 'Tiflis', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Ghana?', 'Acra', 'NOMAD'),
('capitales', '¿Cuál es la capital de Grecia?', 'Atenas', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Guatemala?', 'Ciudad de Guatemala', 'TOURIST'),
('capitales', '¿Cuál es la capital de Guinea?', 'Conakry', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Guinea-Bisáu?', 'Bissau', 'NOMAD'),
('capitales', '¿Cuál es la capital de Guinea Ecuatorial?', 'Malabo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Guyana?', 'Georgetown', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Haití?', 'Puerto Príncipe', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Honduras?', 'Tegucigalpa', 'NOMAD'),
('capitales', '¿Cuál es la capital de Hungría?', 'Budapest', 'NOMAD'),
('capitales', '¿Cuál es la capital de India?', 'Nueva Delhi', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Indonesia?', 'Yakarta', 'TOURIST'),
('capitales', '¿Cuál es la capital de Irak?', 'Bagdad', 'TOURIST'),
('capitales', '¿Cuál es la capital de Irán?', 'Teherán', 'TOURIST'),
('capitales', '¿Cuál es la capital de Irlanda?', 'Dublín', 'TOURIST'),
('capitales', '¿Cuál es la capital de Islandia?', 'Reikiavik', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Israel?', 'Jerusalén', 'TOURIST'),
('capitales', '¿Cuál es la capital de Italia?', 'Roma', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Jamaica?', 'Kingston', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Japón?', 'Tokio', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Jordania?', 'Amán', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Kazajistán?', 'Nurzul', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Kenia?', 'Nairobi', 'NOMAD'),
('capitales', '¿Cuál es la capital de Kirguistán?', 'Biskek', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Kiribati?', 'Tarawa', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Kuwait?', 'Kuwait', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Laos?', 'Vientián', 'NOMAD'),
('capitales', '¿Cuál es la capital de Lesoto?', 'Maseru', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Letonia?', 'Riga', 'NOMAD'),
('capitales', '¿Cuál es la capital de Líbano?', 'Beirut', 'NOMAD'),
('capitales', '¿Cuál es la capital de Liberia?', 'Monrovia', 'NOMAD'),
('capitales', '¿Cuál es la capital de Libia?', 'Trípoli', 'NOMAD'),
('capitales', '¿Cuál es la capital de Liechtenstein?', 'Vaduz', 'NOMAD'),
('capitales', '¿Cuál es la capital de Lituania?', 'Vilna', 'NOMAD'),
('capitales', '¿Cuál es la capital de Luxemburgo?', 'Luxemburgo', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Madagascar?', 'Antananarivo', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Malasia?', 'Kuala Lumpur', 'NOMAD'),
('capitales', '¿Cuál es la capital de Malaui?', 'Lilongwe', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Maldivas?', 'Malé', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Malí?', 'Bamako', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Malta?', 'La Valeta', 'NOMAD'),
('capitales', '¿Cuál es la capital de Marruecos?', 'Rabat', 'TOURIST'),
('capitales', '¿Cuál es la capital de Mauricio?', 'Port Louis', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de México?', 'Ciudad de México', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Micronesia?', 'Palikir', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Moldavia?', 'Chisináu', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Mónaco?', 'Mónaco', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Mongolia?', 'Ulan Bator', 'NOMAD'),
('capitales', '¿Cuál es la capital de Montenegro?', 'Podgorica', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Mozambique?', 'Maputo', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Birmania?', 'Naypyidaw', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Namibia?', 'Windhoek', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Nepal?', 'Katmandú', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Nicaragua?', 'Managua', 'NOMAD'),
('capitales', '¿Cuál es la capital de Níger?', 'Niamey', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Nigeria?', 'Abuya', 'NOMAD'),
('capitales', '¿Cuál es la capital de Noruega?', 'Oslo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Nueva Zelanda?', 'Wellington', 'NOMAD'),
('capitales', '¿Cuál es la capital de Omán?', 'Mascate', 'NOMAD'),
('capitales', '¿Cuál es la capital de Países Bajos?', 'Ámsterdam', 'TOURIST'),
('capitales', '¿Cuál es la capital de Pakistán?', 'Islamabad', 'NOMAD'),
('capitales', '¿Cuál es la capital de Palau?', 'Melekeok', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Panamá?', 'Ciudad de Panamá', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Papúa Nueva Guinea?', 'Port Moresby', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Paraguay?', 'Asunción', 'NOMAD'),
('capitales', '¿Cuál es la capital de Perú?', 'Lima', 'TOURIST'),
('capitales', '¿Cuál es la capital de Polonia?', 'Varsovia', 'TOURIST'),
('capitales', '¿Cuál es la capital de Portugal?', 'Lisboa', 'NOMAD'),
('capitales', '¿Cuál es la capital de Qatar?', 'Doha', 'NOMAD'),
('capitales', '¿Cuál es la capital de Reino Unido?', 'Londres', 'BEGINNER'),
('capitales', '¿Cuál es la capital de República Centroafricana?', 'Bangui', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de República Dominicana?', 'Santo Domingo', 'TOURIST'),
('capitales', '¿Cuál es la capital de Ruanda?', 'Kigali', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Rumanía?', 'Bucarest', 'TOURIST'),
('capitales', '¿Cuál es la capital de Rusia?', 'Moscú', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Samoa?', 'Apia', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de San Cristóbal y Nieves?', 'Basseterre', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de San Marino?', 'San Marino', 'BEGINNER'),
('capitales', '¿Cuál es la capital de San Vicente y las Granadinas?', 'Kingstown', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Santa Lucía?', 'Castries', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Santo Tomé y Príncipe?', 'São Tomé', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Senegal?', 'Dakar', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Serbia?', 'Belgrado', 'NOMAD'),
('capitales', '¿Cuál es la capital de Seychelles?', 'Victoria', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Sierra Leona?', 'Freetown', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Singapur?', 'Singapur', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Siria?', 'Damasco', 'TOURIST'),
('capitales', '¿Cuál es la capital de Somalia?', 'Mogadiscio', 'TOURIST'),
('capitales', '¿Cuál es la capital de Sri Lanka?', 'Sri Jayawardenapura-Kotte', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Suazilandia?', 'Mbabane', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Sudán?', 'Jartum', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Sudán del Sur?', 'Juba', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Suecia?', 'Estocolmo', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Suiza?', 'Berna', 'NOMAD'),
('capitales', '¿Cuál es la capital de Surinam?', 'Paramaribo', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tailandia?', 'Bangkok', 'TOURIST'),
('capitales', '¿Cuál es la capital de Taiwán?', 'Taipei', 'TOURIST'),
('capitales', '¿Cuál es la capital de Tanzania?', 'Dodoma', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tayikistán?', 'Dusambé', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Timor Oriental?', 'Dili', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Togo?', 'Lomé', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tonga?', 'Nukuʻalofa', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Trinidad y Tobago?', 'Puerto España', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Túnez?', 'Túnez', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Turquía?', 'Ankara', 'NOMAD'),
('capitales', '¿Cuál es la capital de Turkmenistán?', 'Ashjabad', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tuvalu?', 'Funafuti', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Ucrania?', 'Kiev', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Uganda?', 'Kampala', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Uruguay?', 'Montevideo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Uzbekistán?', 'Taskent', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Vanuatu?', 'Port Vila', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Venezuela?', 'Caracas', 'TOURIST'),
('capitales', '¿Cuál es la capital de Vietnam?', 'Hanói', 'NOMAD'),
('capitales', '¿Cuál es la capital de Yemen?', 'Saná', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Zambia?', 'Lusaka', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Zimbabue?', 'Harare', 'CARTOGRAPHER');

-- Preguntas de la categoria banderas
INSERT INTO preguntas (category, description, answer, rank, rutaImagen) VALUES
('banderas', '¿A qué país pertenece esta bandera?', 'Afganistán', 'TOURIST', 'es/ies/puerto/img/flags/af.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Albania', 'NOMAD', 'es/ies/puerto/img/flags/al.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Alemania', 'BEGINNER', 'es/ies/puerto/img/flags/de.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Andorra', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/ad.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Angola', 'NOMAD', 'es/ies/puerto/img/flags/ao.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Antigua y Barbuda', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/ag.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Arabia Saudita', 'BEGINNER', 'es/ies/puerto/img/flags/sa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Argentina', 'BEGINNER', 'es/ies/puerto/img/flags/ar.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Armenia', 'NOMAD', 'es/ies/puerto/img/flags/am.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Australia', 'BEGINNER', 'es/ies/puerto/img/flags/au.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Austria', 'TOURIST', 'es/ies/puerto/img/flags/at.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Azerbaiyán', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/az.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bahamas', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/bs.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bahrein', 'NOMAD', 'es/ies/puerto/img/flags/bh.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bangladesh', 'NOMAD', 'es/ies/puerto/img/flags/bd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Barbados', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/bb.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bélgica', 'TOURIST', 'es/ies/puerto/img/flags/be.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Belice', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/bz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Benín', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/bj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bhután', 'NOMAD', 'es/ies/puerto/img/flags/bt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bielorrusia', 'NOMAD', 'es/ies/puerto/img/flags/by.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bolivia', 'NOMAD', 'es/ies/puerto/img/flags/bo.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bosnia y Hrzegovina', 'NOMAD', 'es/ies/puerto/img/flags/ba.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Botsuana', 'NOMAD', 'es/ies/puerto/img/flags/bw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Brasil', 'BEGINNER', 'es/ies/puerto/img/flags/br.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Brunéi', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/bn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bulgaria', 'NOMAD', 'es/ies/puerto/img/flags/bg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Burkina Faso', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/bf.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Burundi', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/bi.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Cabo Verde', 'NOMAD', 'es/ies/puerto/img/flags/cv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Camboya', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/kh.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Camerún', 'NOMAD', 'es/ies/puerto/img/flags/cm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Canadá', 'BEGINNER', 'es/ies/puerto/img/flags/ca.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Catar', 'NOMAD', 'es/ies/puerto/img/flags/qa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Chad', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/td.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Chile', 'TOURIST', 'es/ies/puerto/img/flags/cl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'China', 'BEGINNER', 'es/ies/puerto/img/flags/cn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Chipre', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/cy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ciudad del Vaticano', 'NOMAD', 'es/ies/puerto/img/flags/va.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Colombia', 'TOURIST', 'es/ies/puerto/img/flags/co.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Comoras', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/km.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República del Congo', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/cg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Democrática del Congo', 'NOMAD', 'es/ies/puerto/img/flags/cd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Corea del Norte', 'TOURIST', 'es/ies/puerto/img/flags/kp.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Corea del Sur', 'BEGINNER', 'es/ies/puerto/img/flags/kr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Costa de Marfil', 'NOMAD', 'es/ies/puerto/img/flags/ci.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Costa Rica', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/cr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Croacia', 'NOMAD', 'es/ies/puerto/img/flags/hr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Cuba', 'TOURIST', 'es/ies/puerto/img/flags/cu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Dinamarca', 'TOURIST', 'es/ies/puerto/img/flags/dk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Dominica', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/dm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ecuador', 'NOMAD', 'es/ies/puerto/img/flags/ec.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Egipto', 'TOURIST', 'es/ies/puerto/img/flags/eg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'El Salvador', 'NOMAD', 'es/ies/puerto/img/flags/sv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Emiratos Árabes Unidos', 'TOURIST', 'es/ies/puerto/img/flags/ae.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Eritrea', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/er.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Eslovaquia', 'NOMAD', 'es/ies/puerto/img/flags/sk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Eslovenia', 'NOMAD', 'es/ies/puerto/img/flags/si.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'España', 'BEGINNER', 'es/ies/puerto/img/flags/es.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Estados Unidos', 'BEGINNER', 'es/ies/puerto/img/flags/us.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Estonia', 'NOMAD', 'es/ies/puerto/img/flags/ee.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Etiopía', 'TOURIST', 'es/ies/puerto/img/flags/et.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Fiji', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/fj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Filipinas', 'TOURIST', 'es/ies/puerto/img/flags/ph.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Finlandia', 'NOMAD', 'es/ies/puerto/img/flags/fi.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Francia', 'BEGINNER', 'es/ies/puerto/img/flags/fr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Gabón', 'NOMAD', 'es/ies/puerto/img/flags/ga.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Gambia', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/gm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Georgia', 'NOMAD', 'es/ies/puerto/img/flags/ge.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ghana', 'NOMAD', 'es/ies/puerto/img/flags/gh.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Granada', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/gd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Grecia', 'TOURIST', 'es/ies/puerto/img/flags/gr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guatemala', 'NOMAD', 'es/ies/puerto/img/flags/gt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guinea', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/gn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guinea-Bisáu', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/gw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guinea Ecuatorial', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/gq.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guyana', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/gy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Haití', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/ht.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Honduras', 'NOMAD', 'es/ies/puerto/img/flags/hn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Hungría', 'TOURIST', 'es/ies/puerto/img/flags/hu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'India', 'BEGINNER', 'es/ies/puerto/img/flags/in.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Indonesia', 'TOURIST', 'es/ies/puerto/img/flags/id.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Irak', 'TOURIST', 'es/ies/puerto/img/flags/iq.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Irán', 'TOURIST', 'es/ies/puerto/img/flags/ir.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Irlanda', 'TOURIST', 'es/ies/puerto/img/flags/ie.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Islandia', 'NOMAD', 'es/ies/puerto/img/flags/is.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Israel', 'TOURIST', 'es/ies/puerto/img/flags/il.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Italia', 'BEGINNER', 'es/ies/puerto/img/flags/it.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Jamaica', 'NOMAD', 'es/ies/puerto/img/flags/jm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Japón', 'BEGINNER', 'es/ies/puerto/img/flags/jp.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Jordania', 'NOMAD', 'es/ies/puerto/img/flags/jo.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kazajistán', 'NOMAD', 'es/ies/puerto/img/flags/kz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kenia', 'NOMAD', 'es/ies/puerto/img/flags/ke.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kirguistán', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/kg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kiribati', 'TOURIST', 'es/ies/puerto/img/flags/ki.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kuwait', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/kw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Laos', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/la.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Lesoto', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/ls.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Letonia', 'NOMAD', 'es/ies/puerto/img/flags/lv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Líbano', 'TOURIST', 'es/ies/puerto/img/flags/lb.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Liberia', 'NOMAD', 'es/ies/puerto/img/flags/lr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Libia', 'NOMAD', 'es/ies/puerto/img/flags/ly.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Liechtenstein', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/li.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Lituania', 'NOMAD', 'es/ies/puerto/img/flags/lt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Luxemburgo', 'NOMAD', 'es/ies/puerto/img/flags/lu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Macedonia del Norte', 'NOMAD', 'es/ies/puerto/img/flags/mk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Madagascar', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/mg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malasia', 'NOMAD', 'es/ies/puerto/img/flags/my.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malaui', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/mw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Maldivas', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/mv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malí', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/ml.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malta', 'NOMAD', 'es/ies/puerto/img/flags/mt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Marruecos', 'TOURIST', 'es/ies/puerto/img/flags/ma.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mauricio', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/mu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mauritania', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/mr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'México', 'BEGINNER', 'es/ies/puerto/img/flags/mx.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Micronesia', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/fm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Moldavia', 'NOMAD', 'es/ies/puerto/img/flags/md.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mónaco', 'NOMAD', 'es/ies/puerto/img/flags/mc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mongolia', 'NOMAD', 'es/ies/puerto/img/flags/mn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Montenegro', 'NOMAD', 'es/ies/puerto/img/flags/me.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mozambique', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/mz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Myanmar', 'NOMAD', 'es/ies/puerto/img/flags/mm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Namibia', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/na.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nauru', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/nr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nepal', 'NOMAD', 'es/ies/puerto/img/flags/np.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nicaragua', 'NOMAD', 'es/ies/puerto/img/flags/ni.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Níger', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/ne.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nigeria', 'BEGINNER', 'es/ies/puerto/img/flags/ng.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Noruega', 'TOURIST', 'es/ies/puerto/img/flags/no.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nueva Zelanda', 'TOURIST', 'es/ies/puerto/img/flags/nz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Omán', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/om.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Países Bajos', 'TOURIST', 'es/ies/puerto/img/flags/nl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Pakistán', 'TOURIST', 'es/ies/puerto/img/flags/pk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Palau', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/pw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Panamá', 'NOMAD', 'es/ies/puerto/img/flags/pa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Papúa Nueva Guinea', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/pg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Paraguay', 'NOMAD', 'es/ies/puerto/img/flags/py.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Perú', 'NOMAD', 'es/ies/puerto/img/flags/pe.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Polonia', 'TOURIST', 'es/ies/puerto/img/flags/pl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Portugal', 'TOURIST', 'es/ies/puerto/img/flags/pt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Qatar', 'TOURIST', 'es/ies/puerto/img/flags/qa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Reino Unido', 'BEGINNER', 'es/ies/puerto/img/flags/gb.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Centroafricana', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/cf.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Checa', 'TOURIST', 'es/ies/puerto/img/flags/cz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Democrática del Congo', 'TOURIST', 'es/ies/puerto/img/flags/cd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Dominicana', 'NOMAD', 'es/ies/puerto/img/flags/do.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ruanda', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/rw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Rumanía', 'TOURIST', 'es/ies/puerto/img/flags/ro.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Rusia', 'BEGINNER', 'es/ies/puerto/img/flags/ru.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Samoa', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/ws.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'San Cristóbal y Nieves', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/kn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'San Marino', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/sm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'San Vicente y las Granadinas', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/vc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Santa Lucía', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/lc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Santo Tomé y Príncipe', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/st.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Senegal', 'NOMAD', 'es/ies/puerto/img/flags/sn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Serbia', 'TOURIST', 'es/ies/puerto/img/flags/rs.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Seychelles', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/sc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sierra Leona', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/sl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Singapur', 'NOMAD', 'es/ies/puerto/img/flags/sg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Siria', 'TOURIST', 'es/ies/puerto/img/flags/sy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Somalia', 'NOMAD', 'es/ies/puerto/img/flags/so.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sri Lanka', 'NOMAD', 'es/ies/puerto/img/flags/lk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sudáfrica', 'BEGINNER', 'es/ies/puerto/img/flags/za.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sudán', 'NOMAD', 'es/ies/puerto/img/flags/sd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sudán del Sur', 'TOURIST', 'es/ies/puerto/img/flags/ss.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Suecia', 'TOURIST', 'es/ies/puerto/img/flags/se.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Suiza', 'BEGINNER', 'es/ies/puerto/img/flags/ch.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Surinam', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/sr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tailandia', 'TOURIST', 'es/ies/puerto/img/flags/th.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Taiwán', 'TOURIST', 'es/ies/puerto/img/flags/tw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tanzania', 'NOMAD', 'es/ies/puerto/img/flags/tz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tayikistán', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/tj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Timor Oriental', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/tl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Togo', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/tg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tonga', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/to.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Trinidad y Tobago', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/tt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Túnez', 'NOMAD', 'es/ies/puerto/img/flags/tn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Turquía', 'BEGINNER', 'es/ies/puerto/img/flags/tr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Turkmenistán', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/tm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tuvalu', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/tv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ucrania', 'BEGINNER', 'es/ies/puerto/img/flags/ua.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Uganda', 'NOMAD', 'es/ies/puerto/img/flags/ug.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Uruguay', 'TOURIST', 'es/ies/puerto/img/flags/uy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Uzbekistán', 'NOMAD', 'es/ies/puerto/img/flags/uz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Vanuatu', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/vu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Venezuela', 'TOURIST', 'es/ies/puerto/img/flags/ve.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Vietnam', 'TOURIST', 'es/ies/puerto/img/flags/vn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Yemen', 'NOMAD', 'es/ies/puerto/img/flags/ye.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Yibuti', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/dj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Zambia', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/zm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Zimbabue', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/zw.png');