DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS preguntas;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    country TEXT,
    level INTEGER DEFAULT 0,
    rank TEXT NOT NULL
);

INSERT INTO users (user, email, password, country, level, rank) VALUES
('admin', 'admin@example.com', '1234', 've', 0, 'BEGINNER'),
('john_doe', 'john@example.com', '12345', 'us', 10, 'BEGINNER'),
('alice_w', 'alice@example.com', 'pass123', 'ca', 15, 'BEGINNER'),
('bob_the_builder', 'bob@build.com', 'canwefixit', 'gb', 20, 'BEGINNER'),
('lucy_queen', 'lucy@shine.org', 'crownme', 'es', 25, 'BEGINNER'),
('nina_x', 'nina@nowhere.com', 'securepass', 'de', 5, 'BEGINNER');


CREATE TABLE preguntas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    answer TEXT NOT NULL,
    rank TEXT NOT NULL,
    rutaImagen TEXT
);

-- Preguntas de la categoria capitales
INSERT INTO preguntas (category, description, answer, rank) VALUES
('capitales', '¿Cuál es la capital de Afganistán?', 'Kabul', 'TOURIST'),
('capitales', '¿Cuál es la capital de Albania?', 'Tirana', 'NOMAD'),
('capitales', '¿Cuál es la capital de Alemania?', 'Berlín', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Andorra?', 'Andorra la Vieja', 'NOMAD'),
('capitales', '¿Cuál es la capital de Angola?', 'Luanda', 'NOMAD'),
('capitales', '¿Cuál es la capital de Arabia Saudita?', 'Riad', 'TOURIST'),
('capitales', '¿Cuál es la capital de Argentina?', 'Buenos Aires', 'TOURIST'),
('capitales', '¿Cuál es la capital de Armenia?', 'Ereván', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Australia?', 'Canberra', 'TOURIST'),
('capitales', '¿Cuál es la capital de Austria?', 'Viena', 'NOMAD'),
('capitales', '¿Cuál es la capital de Azerbaiyán?', 'Baku', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Bahrein?', 'Manama', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Bangladesh?', 'Dhaka', 'NOMAD'),
('capitales', '¿Cuál es la capital de Barbados?', 'Bridgetown', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Bielorrusia?', 'Minsk', 'NOMAD'),
('capitales', '¿Cuál es la capital de Bélgica?', 'Bruselas', 'TOURIST'),
('capitales', '¿Cuál es la capital de Belice?', 'Belmopán', 'NOMAD'),
('capitales', '¿Cuál es la capital de Benín?', 'Porto Novo', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Bhutan?', 'Thimphu', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Bosnia y Herzegovina?', 'Sarajevo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Botsuana?', 'Gaborone', 'NOMAD'),
('capitales', '¿Cuál es la capital de Brasil?', 'Brasilia', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Brunei?', 'Bandar Seri Begawan', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Bulgaria?', 'Sofía', 'NOMAD'),
('capitales', '¿Cuál es la capital de Burkina Faso?', 'Ouagadougou', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Burundi?', 'Gitega', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Cabo Verde?', 'Praia', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Camboya?', 'Phnom Penh', 'NOMAD'),
('capitales', '¿Cuál es la capital de Camerún?', 'Yaundé', 'NOMAD'),
('capitales', '¿Cuál es la capital de Canadá?', 'Ottawa', 'TOURIST'),
('capitales', '¿Cuál es la capital de Catar?', 'Doha', 'NOMAD'),
('capitales', '¿Cuál es la capital de Chile?', 'Santiago', 'TOURIST'),
('capitales', '¿Cuál es la capital de China?', 'Pekín', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Chipre?', 'Nicosia', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Ciudad del Vaticano?', 'Ciudad del Vaticano', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Colombia?', 'Bogotá', 'TOURIST'),
('capitales', '¿Cuál es la capital de Comoras?', 'Moroni', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Congo?', 'Brazzaville', 'NOMAD'),
('capitales', '¿Cuál es la capital de República Democrática del Congo?', 'Kinshasa', 'NOMAD'),
('capitales', '¿Cuál es la capital de Corea del Norte?', 'Pionyang', 'TOURIST'),
('capitales', '¿Cuál es la capital de Corea del Sur?', 'Seúl', 'TOURIST'),
('capitales', '¿Cuál es la capital de Costa de Marfil?', 'Yamusukro', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Costa Rica?', 'San José', 'NOMAD'),
('capitales', '¿Cuál es la capital de Croacia?', 'Zagreb', 'NOMAD'),
('capitales', '¿Cuál es la capital de Cuba?', 'La Habana', 'TOURIST'),
('capitales', '¿Cuál es la capital de Dinamarca?', 'Copenhague', 'NOMAD'),
('capitales', '¿Cuál es la capital de Dominica?', 'Roseau', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Ecuador?', 'Quito', 'NOMAD'),
('capitales', '¿Cuál es la capital de Egipto?', 'El Cairo', 'TOURIST'),
('capitales', '¿Cuál es la capital de El Salvador?', 'San Salvador', 'TOURIST'),
('capitales', '¿Cuál es la capital de Emiratos Árabes Unidos?', 'Abu Dhabi', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Eritrea?', 'Asmara', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Eslovaquia?', 'Bratislava', 'NOMAD'),
('capitales', '¿Cuál es la capital de Eslovenia?', 'Liubliana', 'NOMAD'),
('capitales', '¿Cuál es la capital de España?', 'Madrid', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Estados Unidos?', 'Washington D.C.', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Estonia?', 'Tallin', 'NOMAD'),
('capitales', '¿Cuál es la capital de Etiopía?', 'Adís Abeba', 'NOMAD'),
('capitales', '¿Cuál es la capital de Fiji?', 'Suva', 'Aprendiz'),
('capitales', '¿Cuál es la capital de Filipinas?', 'Manila', 'NOMAD'),
('capitales', '¿Cuál es la capital de Finlandia?', 'Helsinki', 'NOMAD'),
('capitales', '¿Cuál es la capital de Francia?', 'París', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Gabón?', 'Libreville', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Gambia?', 'Banjul', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Georgia?', 'Tiflis', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Ghana?', 'Acra', 'NOMAD'),
('capitales', '¿Cuál es la capital de Grecia?', 'Atenas', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Guatemala?', 'Ciudad de Guatemala', 'TOURIST'),
('capitales', '¿Cuál es la capital de Guinea?', 'Conakry', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Guinea-Bisáu?', 'Bissau', 'NOMAD'),
('capitales', '¿Cuál es la capital de Guinea Ecuatorial?', 'Malabo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Guyana?', 'Georgetown', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Haití?', 'Puerto Príncipe', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Honduras?', 'Tegucigalpa', 'NOMAD'),
('capitales', '¿Cuál es la capital de Hungría?', 'Budapest', 'NOMAD'),
('capitales', '¿Cuál es la capital de India?', 'Nueva Delhi', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Indonesia?', 'Yakarta', 'TOURIST'),
('capitales', '¿Cuál es la capital de Irak?', 'Bagdad', 'TOURIST'),
('capitales', '¿Cuál es la capital de Irán?', 'Teherán', 'TOURIST'),
('capitales', '¿Cuál es la capital de Irlanda?', 'Dublín', 'TOURIST'),
('capitales', '¿Cuál es la capital de Islandia?', 'Reikiavik', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Israel?', 'Jerusalén', 'TOURIST'),
('capitales', '¿Cuál es la capital de Italia?', 'Roma', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Jamaica?', 'Kingston', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Japón?', 'Tokio', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Jordania?', 'Amán', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Kazajistán?', 'Nurzul', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Kenia?', 'Nairobi', 'NOMAD'),
('capitales', '¿Cuál es la capital de Kirguistán?', 'Biskek', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Kiribati?', 'Tarawa', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Kuwait?', 'Kuwait', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Laos?', 'Vientián', 'NOMAD'),
('capitales', '¿Cuál es la capital de Lesoto?', 'Maseru', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Letonia?', 'Riga', 'NOMAD'),
('capitales', '¿Cuál es la capital de Líbano?', 'Beirut', 'NOMAD'),
('capitales', '¿Cuál es la capital de Liberia?', 'Monrovia', 'NOMAD'),
('capitales', '¿Cuál es la capital de Libia?', 'Trípoli', 'NOMAD'),
('capitales', '¿Cuál es la capital de Liechtenstein?', 'Vaduz', 'NOMAD'),
('capitales', '¿Cuál es la capital de Lituania?', 'Vilna', 'NOMAD'),
('capitales', '¿Cuál es la capital de Luxemburgo?', 'Luxemburgo', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Madagascar?', 'Antananarivo', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Malasia?', 'Kuala Lumpur', 'NOMAD'),
('capitales', '¿Cuál es la capital de Malaui?', 'Lilongwe', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Maldivas?', 'Malé', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Malí?', 'Bamako', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Malta?', 'La Valeta', 'NOMAD'),
('capitales', '¿Cuál es la capital de Marruecos?', 'Rabat', 'TOURIST'),
('capitales', '¿Cuál es la capital de Mauricio?', 'Port Louis', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de México?', 'Ciudad de México', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Micronesia?', 'Palikir', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Moldavia?', 'Chisináu', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Mónaco?', 'Mónaco', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Mongolia?', 'Ulan Bator', 'NOMAD'),
('capitales', '¿Cuál es la capital de Montenegro?', 'Podgorica', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Mozambique?', 'Maputo', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Birmania?', 'Naypyidaw', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Namibia?', 'Windhoek', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Nepal?', 'Katmandú', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Nicaragua?', 'Managua', 'NOMAD'),
('capitales', '¿Cuál es la capital de Níger?', 'Niamey', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Nigeria?', 'Abuya', 'NOMAD'),
('capitales', '¿Cuál es la capital de Noruega?', 'Oslo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Nueva Zelanda?', 'Wellington', 'NOMAD'),
('capitales', '¿Cuál es la capital de Omán?', 'Mascate', 'NOMAD'),
('capitales', '¿Cuál es la capital de Países Bajos?', 'Ámsterdam', 'TOURIST'),
('capitales', '¿Cuál es la capital de Pakistán?', 'Islamabad', 'NOMAD'),
('capitales', '¿Cuál es la capital de Palau?', 'Melekeok', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Panamá?', 'Ciudad de Panamá', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Papúa Nueva Guinea?', 'Port Moresby', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Paraguay?', 'Asunción', 'NOMAD'),
('capitales', '¿Cuál es la capital de Perú?', 'Lima', 'TOURIST'),
('capitales', '¿Cuál es la capital de Polonia?', 'Varsovia', 'TOURIST'),
('capitales', '¿Cuál es la capital de Portugal?', 'Lisboa', 'NOMAD'),
('capitales', '¿Cuál es la capital de Qatar?', 'Doha', 'NOMAD'),
('capitales', '¿Cuál es la capital de Reino Unido?', 'Londres', 'BEGINNER'),
('capitales', '¿Cuál es la capital de República Centroafricana?', 'Bangui', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de República Dominicana?', 'Santo Domingo', 'TOURIST'),
('capitales', '¿Cuál es la capital de Ruanda?', 'Kigali', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Rumanía?', 'Bucarest', 'TOURIST'),
('capitales', '¿Cuál es la capital de Rusia?', 'Moscú', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Samoa?', 'Apia', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de San Cristóbal y Nieves?', 'Basseterre', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de San Marino?', 'San Marino', 'BEGINNER'),
('capitales', '¿Cuál es la capital de San Vicente y las Granadinas?', 'Kingstown', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Santa Lucía?', 'Castries', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Santo Tomé y Príncipe?', 'São Tomé', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Senegal?', 'Dakar', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Serbia?', 'Belgrado', 'NOMAD'),
('capitales', '¿Cuál es la capital de Seychelles?', 'Victoria', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Sierra Leona?', 'Freetown', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Singapur?', 'Singapur', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Siria?', 'Damasco', 'TOURIST'),
('capitales', '¿Cuál es la capital de Somalia?', 'Mogadiscio', 'TOURIST'),
('capitales', '¿Cuál es la capital de Sri Lanka?', 'Sri Jayawardenapura-Kotte', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Suazilandia?', 'Mbabane', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Sudán?', 'Jartum', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Sudán del Sur?', 'Juba', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Suecia?', 'Estocolmo', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Suiza?', 'Berna', 'NOMAD'),
('capitales', '¿Cuál es la capital de Surinam?', 'Paramaribo', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tailandia?', 'Bangkok', 'TOURIST'),
('capitales', '¿Cuál es la capital de Taiwán?', 'Taipei', 'TOURIST'),
('capitales', '¿Cuál es la capital de Tanzania?', 'Dodoma', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tayikistán?', 'Dusambé', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Timor Oriental?', 'Dili', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Togo?', 'Lomé', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tonga?', 'Nukuʻalofa', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Trinidad y Tobago?', 'Puerto España', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Túnez?', 'Túnez', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Turquía?', 'Ankara', 'NOMAD'),
('capitales', '¿Cuál es la capital de Turkmenistán?', 'Ashjabad', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Tuvalu?', 'Funafuti', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Ucrania?', 'Kiev', 'BEGINNER'),
('capitales', '¿Cuál es la capital de Uganda?', 'Kampala', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Uruguay?', 'Montevideo', 'NOMAD'),
('capitales', '¿Cuál es la capital de Uzbekistán?', 'Taskent', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Vanuatu?', 'Port Vila', 'CARTOGRAPH_MASTER'),
('capitales', '¿Cuál es la capital de Venezuela?', 'Caracas', 'TOURIST'),
('capitales', '¿Cuál es la capital de Vietnam?', 'Hanói', 'NOMAD'),
('capitales', '¿Cuál es la capital de Yemen?', 'Saná', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Zambia?', 'Lusaka', 'CARTOGRAPHER'),
('capitales', '¿Cuál es la capital de Zimbabue?', 'Harare', 'CARTOGRAPHER');

-- Preguntas de la categoria banderas
INSERT INTO preguntas (category, description, answer, rank, rutaImagen) VALUES
('banderas', '¿A qué país pertenece esta bandera?', 'Afganistán', 'TOURIST', '/es/ies/puerto/img/flags/af.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Albania', 'NOMAD', '/es/ies/puerto/img/flags/al.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Alemania', 'BEGINNER', '/es/ies/puerto/img/flags/de.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Andorra', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/ad.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Angola', 'NOMAD', '/es/ies/puerto/img/flags/ao.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Antigua y Barbuda', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/ag.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Arabia Saudita', 'BEGINNER', 'es/ies/puerto/img/flags/sa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Argentina', 'BEGINNER', '/es/ies/puerto/img/flags/ar.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Armenia', 'NOMAD', '/es/ies/puerto/img/flags/am.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Australia', 'BEGINNER', '/es/ies/puerto/img/flags/au.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Austria', 'TOURIST', '/es/ies/puerto/img/flags/at.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Azerbaiyán', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/az.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bahamas', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/bs.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bahrein', 'NOMAD', '/es/ies/puerto/img/flags/bh.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bangladesh', 'NOMAD', '/es/ies/puerto/img/flags/bd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Barbados', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/bb.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bélgica', 'TOURIST', '/es/ies/puerto/img/flags/be.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Belice', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/bz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Benín', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/bj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bhután', 'NOMAD', '/es/ies/puerto/img/flags/bt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bielorrusia', 'NOMAD', '/es/ies/puerto/img/flags/by.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bolivia', 'NOMAD', '/es/ies/puerto/img/flags/bo.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bosnia y Hrzegovina', 'NOMAD', '/es/ies/puerto/img/flags/ba.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Botsuana', 'NOMAD', '/es/ies/puerto/img/flags/bw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Brasil', 'BEGINNER', '/es/ies/puerto/img/flags/br.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Brunéi', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/bn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Bulgaria', 'NOMAD', '/es/ies/puerto/img/flags/bg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Burkina Faso', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/bf.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Burundi', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/bi.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Cabo Verde', 'NOMAD', '/es/ies/puerto/img/flags/cv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Camboya', 'CARTOGRAPHER', 'es/ies/puerto/img/flags/kh.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Camerún', 'NOMAD', '/es/ies/puerto/img/flags/cm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Canadá', 'BEGINNER', '/es/ies/puerto/img/flags/ca.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Catar', 'NOMAD', '/es/ies/puerto/img/flags/qa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Chad', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/td.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Chile', 'TOURIST', '/es/ies/puerto/img/flags/cl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'China', 'BEGINNER', '/es/ies/puerto/img/flags/cn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Chipre', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/cy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ciudad del Vaticano', 'NOMAD', '/es/ies/puerto/img/flags/va.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Colombia', 'TOURIST', '/es/ies/puerto/img/flags/co.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Comoras', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/km.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República del Congo', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/cg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Democrática del Congo', 'NOMAD', '/es/ies/puerto/img/flags/cd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Corea del Norte', 'TOURIST', '/es/ies/puerto/img/flags/kp.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Corea del Sur', 'BEGINNER', '/es/ies/puerto/img/flags/kr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Costa de Marfil', 'NOMAD', '/es/ies/puerto/img/flags/ci.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Costa Rica', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/cr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Croacia', 'NOMAD', '/es/ies/puerto/img/flags/hr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Cuba', 'TOURIST', '/es/ies/puerto/img/flags/cu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Dinamarca', 'TOURIST', '/es/ies/puerto/img/flags/dk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Dominica', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/dm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ecuador', 'NOMAD', '/es/ies/puerto/img/flags/ec.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Egipto', 'TOURIST', '/es/ies/puerto/img/flags/eg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'El Salvador', 'NOMAD', '/es/ies/puerto/img/flags/sv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Emiratos Árabes Unidos', 'TOURIST', '/es/ies/puerto/img/flags/ae.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Eritrea', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/er.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Eslovaquia', 'NOMAD', '/es/ies/puerto/img/flags/sk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Eslovenia', 'NOMAD', '/es/ies/puerto/img/flags/si.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'España', 'BEGINNER', '/es/ies/puerto/img/flags/es.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Estados Unidos', 'BEGINNER', '/es/ies/puerto/img/flags/us.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Estonia', 'NOMAD', '/es/ies/puerto/img/flags/ee.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Etiopía', 'TOURIST', '/es/ies/puerto/img/flags/et.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Fiji', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/fj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Filipinas', 'TOURIST', '/es/ies/puerto/img/flags/ph.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Finlandia', 'NOMAD', '/es/ies/puerto/img/flags/fi.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Francia', 'BEGINNER', '/es/ies/puerto/img/flags/fr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Gabón', 'NOMAD', '/es/ies/puerto/img/flags/ga.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Gambia', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/gm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Georgia', 'NOMAD', '/es/ies/puerto/img/flags/ge.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ghana', 'NOMAD', '/es/ies/puerto/img/flags/gh.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Granada', 'CARTOGRAPH_MASTER', 'es/ies/puerto/img/flags/gd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Grecia', 'TOURIST', '/es/ies/puerto/img/flags/gr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guatemala', 'NOMAD', '/es/ies/puerto/img/flags/gt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guinea', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/gn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guinea-Bisáu', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/gw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guinea Ecuatorial', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/gq.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Guyana', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/gy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Haití', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/ht.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Honduras', 'NOMAD', '/es/ies/puerto/img/flags/hn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Hungría', 'TOURIST', '/es/ies/puerto/img/flags/hu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'India', 'BEGINNER', '/es/ies/puerto/img/flags/in.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Indonesia', 'TOURIST', 'es/ies/puerto/img/flags/id.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Irak', 'TOURIST', '/es/ies/puerto/img/flags/iq.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Irán', 'TOURIST', '/es/ies/puerto/img/flags/ir.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Irlanda', 'TOURIST', '/es/ies/puerto/img/flags/ie.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Islandia', 'NOMAD', '/es/ies/puerto/img/flags/is.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Israel', 'TOURIST', '/es/ies/puerto/img/flags/il.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Italia', 'BEGINNER', '/es/ies/puerto/img/flags/it.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Jamaica', 'NOMAD', '/es/ies/puerto/img/flags/jm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Japón', 'BEGINNER', '/es/ies/puerto/img/flags/jp.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Jordania', 'NOMAD', '/es/ies/puerto/img/flags/jo.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kazajistán', 'NOMAD', '/es/ies/puerto/img/flags/kz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kenia', 'NOMAD', '/es/ies/puerto/img/flags/ke.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kirguistán', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/kg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kiribati', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/ki.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Kuwait', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/kw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Laos', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/la.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Lesoto', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/ls.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Letonia', 'NOMAD', '/es/ies/puerto/img/flags/lv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Líbano', 'TOURIST', '/es/ies/puerto/img/flags/lb.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Libia', 'NOMAD', '/es/ies/puerto/img/flags/ly.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Liechtenstein', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/li.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Lituania', 'NOMAD', '/es/ies/puerto/img/flags/lt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Luxemburgo', 'NOMAD', '/es/ies/puerto/img/flags/lu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Macedonia del Norte', 'NOMAD', '/es/ies/puerto/img/flags/mk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Madagascar', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/mg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malasia', 'NOMAD', '/es/ies/puerto/img/flags/my.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malaui', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/mw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Maldivas', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/mv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malí', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/ml.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Malta', 'NOMAD', '/es/ies/puerto/img/flags/mt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Marruecos', 'TOURIST', '/es/ies/puerto/img/flags/ma.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mauricio', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/mu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mauritania', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/mr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'México', 'BEGINNER', '/es/ies/puerto/img/flags/mx.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Micronesia', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/fm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Moldavia', 'NOMAD', '/es/ies/puerto/img/flags/md.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mónaco', 'NOMAD', '/es/ies/puerto/img/flags/mc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mongolia', 'NOMAD', '/es/ies/puerto/img/flags/mn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Montenegro', 'NOMAD', '/es/ies/puerto/img/flags/me.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Mozambique', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/mz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Myanmar', 'NOMAD', '/es/ies/puerto/img/flags/mm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Namibia', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/na.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nauru', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/nr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nepal', 'NOMAD', '/es/ies/puerto/img/flags/np.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nicaragua', 'NOMAD', '/es/ies/puerto/img/flags/ni.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Níger', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/ne.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nigeria', 'BEGINNER', '/es/ies/puerto/img/flags/ng.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Noruega', 'TOURIST', '/es/ies/puerto/img/flags/no.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Nueva Zelanda', 'TOURIST', '/es/ies/puerto/img/flags/nz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Omán', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/om.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Países Bajos', 'TOURIST', '/es/ies/puerto/img/flags/nl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Pakistán', 'TOURIST', '/es/ies/puerto/img/flags/pk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Palau', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/pw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Panamá', 'NOMAD', '/es/ies/puerto/img/flags/pa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Papúa Nueva Guinea', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/pg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Paraguay', 'NOMAD', '/es/ies/puerto/img/flags/py.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Perú', 'NOMAD', '/es/ies/puerto/img/flags/pe.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Polonia', 'TOURIST', '/es/ies/puerto/img/flags/pl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Portugal', 'TOURIST', '/es/ies/puerto/img/flags/pt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Qatar', 'TOURIST', '/es/ies/puerto/img/flags/qa.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Reino Unido', 'BEGINNER', '/es/ies/puerto/img/flags/gb.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Centroafricana', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/cf.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Checa', 'TOURIST', '/es/ies/puerto/img/flags/cz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Democrática del Congo', 'TOURIST', '/es/ies/puerto/img/flags/cd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'República Dominicana', 'NOMAD', '/es/ies/puerto/img/flags/do.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ruanda', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/rw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Rumanía', 'TOURIST', '/es/ies/puerto/img/flags/ro.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Rusia', 'BEGINNER', '/es/ies/puerto/img/flags/ru.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Samoa', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/ws.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'San Cristóbal y Nieves', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/kn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'San Marino', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/sm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'San Vicente y las Granadinas', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/vc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Santa Lucía', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/lc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Santo Tomé y Príncipe', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/st.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Senegal', 'NOMAD', '/es/ies/puerto/img/flags/sn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Serbia', 'TOURIST', '/es/ies/puerto/img/flags/rs.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Seychelles', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/sc.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sierra Leona', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/sl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Singapur', 'NOMAD', '/es/ies/puerto/img/flags/sg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Siria', 'TOURIST', '/es/ies/puerto/img/flags/sy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Somalia', 'NOMAD', '/es/ies/puerto/img/flags/so.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sri Lanka', 'NOMAD', '/es/ies/puerto/img/flags/lk.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sudáfrica', 'BEGINNER', '/es/ies/puerto/img/flags/za.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sudán', 'NOMAD', '/es/ies/puerto/img/flags/sd.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Sudán del Sur', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/ss.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Suecia', 'TOURIST', '/es/ies/puerto/img/flags/se.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Suiza', 'BEGINNER', '/es/ies/puerto/img/flags/ch.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Surinam', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/sr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tailandia', 'TOURIST', '/es/ies/puerto/img/flags/th.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Taiwán', 'TOURIST', '/es/ies/puerto/img/flags/tw.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tanzania', 'NOMAD', '/es/ies/puerto/img/flags/tz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tayikistán', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/tj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Timor Oriental', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/tl.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Togo', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/tg.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tonga', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/to.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Trinidad y Tobago', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/tt.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Túnez', 'NOMAD', '/es/ies/puerto/img/flags/tn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Turquía', 'BEGINNER', '/es/ies/puerto/img/flags/tr.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Turkmenistán', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/tm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Tuvalu', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/tv.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Ucrania', 'BEGINNER', '/es/ies/puerto/img/flags/ua.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Uganda', 'NOMAD', '/es/ies/puerto/img/flags/ug.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Uruguay', 'TOURIST', '/es/ies/puerto/img/flags/uy.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Uzbekistán', 'NOMAD', '/es/ies/puerto/img/flags/uz.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Vanuatu', 'CARTOGRAPH_MASTER', '/Es/ies/puerto/img/flags/vu.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Venezuela', 'TOURIST', '/es/ies/puerto/img/flags/ve.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Vietnam', 'TOURIST', '/es/ies/puerto/img/flags/vn.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Yemen', 'NOMAD', '/es/ies/puerto/img/flags/ye.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Yibuti', 'CARTOGRAPH_MASTER', '/es/ies/puerto/img/flags/dj.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Zambia', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/zm.png'),
('banderas', '¿A qué país pertenece esta bandera?', 'Zimbabue', 'CARTOGRAPHER', '/es/ies/puerto/img/flags/zw.png');

-- Preguntas de la categoria poblacion
INSERT INTO preguntas (category, description, answer, rank) VALUES
('poblacion', '¿Cuál es la población de Afganistán? Responde en cifras de millón', '42', 'TOURIST'),
('poblacion', '¿Cuál es la población de Albania? Responde en cifras de millón', '2.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Alemania? Responde en cifras de millón', '83', 'TOURIST'),
('poblacion', '¿Cuál es la población de Andorra? Responde en cifras de millón', '0.08', 'TOURIST'),
('poblacion', '¿Cuál es la población de Angola? Responde en cifras de millón', '34', 'TOURIST'),
('poblacion', '¿Cuál es la población de Antigua y Barbuda? Responde en cifras de millón', '0.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Arabia Saudita? Responde en cifras de millón', '36', 'TOURIST'),
('poblacion', '¿Cuál es la población de Argelia? Responde en cifras de millón', '45', 'TOURIST'),
('poblacion', '¿Cuál es la población de Argentina? Responde en cifras de millón', '46', 'TOURIST'),
('poblacion', '¿Cuál es la población de Armenia? Responde en cifras de millón', '3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Australia? Responde en cifras de millón', '26', 'TOURIST'),
('poblacion', '¿Cuál es la población de Austria? Responde en cifras de millón', '9', 'TOURIST'),
('poblacion', '¿Cuál es la población de Azerbaiyán? Responde en cifras de millón', '10', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bahamas? Responde en cifras de millón', '0.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bangladés? Responde en cifras de millón', '170', 'TOURIST'),
('poblacion', '¿Cuál es la población de Barbados? Responde en cifras de millón', '0.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Baréin? Responde en cifras de millón', '1.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bélgica? Responde en cifras de millón', '11', 'TOURIST'),
('poblacion', '¿Cuál es la población de Belice? Responde en cifras de millón', '0.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Benín? Responde en cifras de millón', '13', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bielorrusia? Responde en cifras de millón', '9.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Birmania (Myanmar)? Responde en cifras de millón', '54', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bolivia? Responde en cifras de millón', '12', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bosnia y Herzegovina? Responde en cifras de millón', '3.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Botsuana? Responde en cifras de millón', '2.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Brasil? Responde en cifras de millón', '215', 'BEGINNER'),
('poblacion', '¿Cuál es la población de Brunéi? Responde en cifras de millón', '0.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bulgaria? Responde en cifras de millón', '6.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Burkina Faso? Responde en cifras de millón', '22', 'TOURIST'),
('poblacion', '¿Cuál es la población de Burundi? Responde en cifras de millón', '12', 'TOURIST'),
('poblacion', '¿Cuál es la población de Bután? Responde en cifras de millón', '0.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Cabo Verde? Responde en cifras de millón', '0.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Camboya? Responde en cifras de millón', '17', 'TOURIST'),
('poblacion', '¿Cuál es la población de Camerún? Responde en cifras de millón', '27', 'TOURIST'),
('poblacion', '¿Cuál es la población de Canadá? Responde en cifras de millón', '38', 'TOURIST'),
('poblacion', '¿Cuál es la población de Catar? Responde en cifras de millón', '2.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Chad? Responde en cifras de millón', '17', 'TOURIST'),
('poblacion', '¿Cuál es la población de Chile? Responde en cifras de millón', '19', 'TOURIST'),
('poblacion', '¿Cuál es la población de China? Responde en cifras de millón', '1412', 'TOURIST'),
('poblacion', '¿Cuál es la población de Chipre? Responde en cifras de millón', '1.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Colombia? Responde en cifras de millón', '52', 'TOURIST'),
('poblacion', '¿Cuál es la población de Comoras? Responde en cifras de millón', '0.9', 'TOURIST'),
('poblacion', '¿Cuál es la población de Corea del Norte? Responde en cifras de millón', '26', 'TOURIST'),
('poblacion', '¿Cuál es la población de Corea del Sur? Responde en cifras de millón', '51', 'TOURIST'),
('poblacion', '¿Cuál es la población de Costa de Marfil? Responde en cifras de millón', '27', 'TOURIST'),
('poblacion', '¿Cuál es la población de Costa Rica? Responde en cifras de millón', '5.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Croacia? Responde en cifras de millón', '4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Cuba? Responde en cifras de millón', '11', 'TOURIST'),
('poblacion', '¿Cuál es la población de Dinamarca? Responde en cifras de millón', '5.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Dominica? Responde en cifras de millón', '0.07', 'TOURIST'),
('poblacion', '¿Cuál es la población de Ecuador? Responde en cifras de millón', '18', 'TOURIST'),
('poblacion', '¿Cuál es la población de Egipto? Responde en cifras de millón', '109', 'TOURIST'),
('poblacion', '¿Cuál es la población de El Salvador? Responde en cifras de millón', '6.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Emiratos Árabes Unidos? Responde en cifras de millón', '10', 'TOURIST'),
('poblacion', '¿Cuál es la población de Eritrea? Responde en cifras de millón', '3.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Eslovaquia? Responde en cifras de millón', '5.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Eslovenia? Responde en cifras de millón', '2.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de España? Responde en cifras de millón', '47', 'TOURIST'),
('poblacion', '¿Cuál es la población de Estados Unidos? Responde en cifras de millón', '331', 'TOURIST'),
('poblacion', '¿Cuál es la población de Estonia? Responde en cifras de millón', '1.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Eswatini? Responde en cifras de millón', '1.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Etiopía? Responde en cifras de millón', '123', 'TOURIST'),
('poblacion', '¿Cuál es la población de Filipinas? Responde en cifras de millón', '115', 'TOURIST'),
('poblacion', '¿Cuál es la población de Finlandia? Responde en cifras de millón', '5.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Fiyi? Responde en cifras de millón', '0.9', 'TOURIST'),
('poblacion', '¿Cuál es la población de Francia? Responde en cifras de millón', '68', 'TOURIST'),
('poblacion', '¿Cuál es la población de Gabón? Responde en cifras de millón', '2.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Gambia? Responde en cifras de millón', '2.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Georgia? Responde en cifras de millón', '3.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de Ghana? Responde en cifras de millón', '32', 'TOURIST'),
('poblacion', '¿Cuál es la población de Granada? Responde en cifras de millón', '0.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Grecia? Responde en cifras de millón', '10', 'TOURIST'),
('poblacion', '¿Cuál es la población de Guatemala? Responde en cifras de millón', '18', 'TOURIST'),
('poblacion', '¿Cuál es la población de Guinea? Responde en cifras de millón', '13', 'TOURIST'),
('poblacion', '¿Cuál es la población de Guinea-Bisáu? Responde en cifras de millón', '2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Guinea Ecuatorial? Responde en cifras de millón', '1.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Guyana? Responde en cifras de millón', '0.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Haití? Responde en cifras de millón', '11', 'TOURIST'),
('poblacion', '¿Cuál es la población de Honduras? Responde en cifras de millón', '10', 'TOURIST'),
('poblacion', '¿Cuál es la población de Hungría? Responde en cifras de millón', '9.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de India? Responde en cifras de millón', '1408', 'TOURIST'),
('poblacion', '¿Cuál es la población de Indonesia? Responde en cifras de millón', '275', 'TOURIST'),
('poblacion', '¿Cuál es la población de Irak? Responde en cifras de millón', '43', 'TOURIST'),
('poblacion', '¿Cuál es la población de Irán? Responde en cifras de millón', '87', 'TOURIST'),
('poblacion', '¿Cuál es la población de Irlanda? Responde en cifras de millón', '5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Islandia? Responde en cifras de millón', '0.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Islas Marshall? Responde en cifras de millón', '0.06', 'TOURIST'),
('poblacion', '¿Cuál es la población de Islas Salomón? Responde en cifras de millón', '0.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de Israel? Responde en cifras de millón', '9.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Italia? Responde en cifras de millón', '59', 'TOURIST'),
('poblacion', '¿Cuál es la población de Jamaica? Responde en cifras de millón', '2.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Japón? Responde en cifras de millón', '125', 'TOURIST'),
('poblacion', '¿Cuál es la población de Jordania? Responde en cifras de millón', '11', 'TOURIST'),
('poblacion', '¿Cuál es la población de Kazajistán? Responde en cifras de millón', '19', 'TOURIST'),
('poblacion', '¿Cuál es la población de Kenia? Responde en cifras de millón', '55', 'TOURIST'),
('poblacion', '¿Cuál es la población de Kirguistán? Responde en cifras de millón', '6.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de Kiribati? Responde en cifras de millón', '0.12', 'TOURIST'),
('poblacion', '¿Cuál es la población de Kuwait? Responde en cifras de millón', '4.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Laos? Responde en cifras de millón', '7.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Lesoto? Responde en cifras de millón', '2.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Letonia? Responde en cifras de millón', '1.9', 'TOURIST'),
('poblacion', '¿Cuál es la población de Líbano? Responde en cifras de millón', '5.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Liberia? Responde en cifras de millón', '5.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Libia? Responde en cifras de millón', '6.9', 'TOURIST'),
('poblacion', '¿Cuál es la población de Liechtenstein? Responde en cifras de millón', '0.04', 'TOURIST'),
('poblacion', '¿Cuál es la población de Lituania? Responde en cifras de millón', '2.8', 'TOURIST'),
('poblacion', '¿Cuál es la población de Luxemburgo? Responde en cifras de millón', '0.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Madagascar? Responde en cifras de millón', '28', 'TOURIST'),
('poblacion', '¿Cuál es la población de Malasia? Responde en cifras de millón', '33', 'TOURIST'),
('poblacion', '¿Cuál es la población de Malaui? Responde en cifras de millón', '20', 'TOURIST'),
('poblacion', '¿Cuál es la población de Maldivas? Responde en cifras de millón', '0.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Malí? Responde en cifras de millón', '22', 'TOURIST'),
('poblacion', '¿Cuál es la población de Malta? Responde en cifras de millón', '0.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Marruecos? Responde en cifras de millón', '37', 'TOURIST'),
('poblacion', '¿Cuál es la población de Mauricio? Responde en cifras de millón', '1.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Mauritania? Responde en cifras de millón', '4.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de México? Responde en cifras de millón', '129', 'TOURIST'),
('poblacion', '¿Cuál es la población de Micronesia? Responde en cifras de millón', '0.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Moldavia? Responde en cifras de millón', '2.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Mónaco? Responde en cifras de millón', '0.04', 'TOURIST'),
('poblacion', '¿Cuál es la población de Mongolia? Responde en cifras de millón', '3.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Montenegro? Responde en cifras de millón', '0.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Mozambique? Responde en cifras de millón', '32', 'TOURIST'),
('poblacion', '¿Cuál es la población de Namibia? Responde en cifras de millón', '2.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Nauru? Responde en cifras de millón', '0.01', 'TOURIST'),
('poblacion', '¿Cuál es la población de Nepal? Responde en cifras de millón', '30', 'TOURIST'),
('poblacion', '¿Cuál es la población de Nicaragua? Responde en cifras de millón', '6.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de Níger? Responde en cifras de millón', '25', 'TOURIST'),
('poblacion', '¿Cuál es la población de Nigeria? Responde en cifras de millón', '223', 'TOURIST'),
('poblacion', '¿Cuál es la población de Noruega? Responde en cifras de millón', '5.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Nueva Zelanda? Responde en cifras de millón', '5.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Omán? Responde en cifras de millón', '4.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Países Bajos? Responde en cifras de millón', '17', 'TOURIST'),
('poblacion', '¿Cuál es la población de Pakistán? Responde en cifras de millón', '240', 'TOURIST'),
('poblacion', '¿Cuál es la población de Palaos? Responde en cifras de millón', '0.02', 'TOURIST'),
('poblacion', '¿Cuál es la población de Panamá? Responde en cifras de millón', '4.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Papúa Nueva Guinea? Responde en cifras de millón', '9.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Paraguay? Responde en cifras de millón', '7.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Perú? Responde en cifras de millón', '34', 'TOURIST'),
('poblacion', '¿Cuál es la población de Polonia? Responde en cifras de millón', '38', 'TOURIST'),
('poblacion', '¿Cuál es la población de Portugal? Responde en cifras de millón', '10', 'TOURIST'),
('poblacion', '¿Cuál es la población de Reino Unido? Responde en cifras de millón', '67', 'TOURIST'),
('poblacion', '¿Cuál es la población de República Centroafricana? Responde en cifras de millón', '5.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de República Checa? Responde en cifras de millón', '10', 'TOURIST'),
('poblacion', '¿Cuál es la población de República del Congo? Responde en cifras de millón', '5.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de República Democrática del Congo? Responde en cifras de millón', '99', 'TOURIST'),
('poblacion', '¿Cuál es la población de República Dominicana? Responde en cifras de millón', '11', 'TOURIST'),
('poblacion', '¿Cuál es la población de Ruanda? Responde en cifras de millón', '13', 'TOURIST'),
('poblacion', '¿Cuál es la población de Rumanía? Responde en cifras de millón', '19', 'TOURIST'),
('poblacion', '¿Cuál es la población de Rusia? Responde en cifras de millón', '144', 'TOURIST'),
('poblacion', '¿Cuál es la población de Samoa? Responde en cifras de millón', '0.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de San Cristóbal y Nieves? Responde en cifras de millón', '0.05', 'TOURIST'),
('poblacion', '¿Cuál es la población de San Marino? Responde en cifras de millón', '0.03', 'TOURIST'),
('poblacion', '¿Cuál es la población de San Vicente y las Granadinas? Responde en cifras de millón', '0.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Santa Lucía? Responde en cifras de millón', '0.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Santo Tomé y Príncipe? Responde en cifras de millón', '0.2', 'TOURIST'),
('poblacion', '¿Cuál es la población de Senegal? Responde en cifras de millón', '17', 'TOURIST'),
('poblacion', '¿Cuál es la población de Serbia? Responde en cifras de millón', '6.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de Seychelles? Responde en cifras de millón', '0.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Sierra Leona? Responde en cifras de millón', '8.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Singapur? Responde en cifras de millón', '5.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de Siria? Responde en cifras de millón', '21', 'TOURIST'),
('poblacion', '¿Cuál es la población de Somalia? Responde en cifras de millón', '17', 'TOURIST'),
('poblacion', '¿Cuál es la población de Sri Lanka? Responde en cifras de millón', '22', 'TOURIST'),
('poblacion', '¿Cuál es la población de Sudáfrica? Responde en cifras de millón', '60', 'TOURIST'),
('poblacion', '¿Cuál es la población de Sudán? Responde en cifras de millón', '46', 'TOURIST'),
('poblacion', '¿Cuál es la población de Sudán del Sur? Responde en cifras de millón', '11', 'TOURIST'),
('poblacion', '¿Cuál es la población de Suecia? Responde en cifras de millón', '10', 'TOURIST'),
('poblacion', '¿Cuál es la población de Suiza? Responde en cifras de millón', '8.7', 'TOURIST'),
('poblacion', '¿Cuál es la población de Surinam? Responde en cifras de millón', '0.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Tailandia? Responde en cifras de millón', '70', 'TOURIST'),
('poblacion', '¿Cuál es la población de Tanzania? Responde en cifras de millón', '63', 'TOURIST'),
('poblacion', '¿Cuál es la población de Tayikistán? Responde en cifras de millón', '9.9', 'TOURIST'),
('poblacion', '¿Cuál es la población de Timor Oriental? Responde en cifras de millón', '1.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Togo? Responde en cifras de millón', '8.6', 'TOURIST'),
('poblacion', '¿Cuál es la población de Tonga? Responde en cifras de millón', '0.1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Trinidad y Tobago? Responde en cifras de millón', '1.4', 'TOURIST'),
('poblacion', '¿Cuál es la población de Túnez? Responde en cifras de millón', '12', 'TOURIST'),
('poblacion', '¿Cuál es la población de Turkmenistán? Responde en cifras de millón', '6.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Turquía? Responde en cifras de millón', '85', 'TOURIST'),
('poblacion', '¿Cuál es la población de Tuvalu? Responde en cifras de millón', '0.01', 'TOURIST'),
('poblacion', '¿Cuál es la población de Ucrania? Responde en cifras de millón', '37', 'TOURIST'),
('poblacion', '¿Cuál es la población de Uganda? Responde en cifras de millón', '47', 'TOURIST'),
('poblacion', '¿Cuál es la población de Uruguay? Responde en cifras de millón', '3.5', 'TOURIST'),
('poblacion', '¿Cuál es la población de Uzbekistán? Responde en cifras de millón', '35', 'TOURIST'),
('poblacion', '¿Cuál es la población de Vanuatu? Responde en cifras de millón', '0.3', 'TOURIST'),
('poblacion', '¿Cuál es la población de Vaticano? Responde en cifras de millón', '0.0008', 'TOURIST'),
('poblacion', '¿Cuál es la población de Venezuela? Responde en cifras de millón', '28', 'TOURIST'),
('poblacion', '¿Cuál es la población de Vietnam? Responde en cifras de millón', '99', 'TOURIST'),
('poblacion', '¿Cuál es la población de Yemen? Responde en cifras de millón', '33', 'TOURIST'),
('poblacion', '¿Cuál es la población de Yibuti? Responde en cifras de millón', '1', 'TOURIST'),
('poblacion', '¿Cuál es la población de Zambia? Responde en cifras de millón', '19', 'TOURIST'),
('poblacion', '¿Cuál es la población de Zimbabue? Responde en cifras de millón', '15', 'TOURIST');

-- Peguntad de la 
INSERT INTO preguntas (category, description, answer, rank) VALUES
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Estados Unidos? Responde en cifras de miles de millón', '26700', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de China? Responde en cifras de miles de millón', '19300', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Alemania? Responde en cifras de miles de millón', '4300', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Japón? Responde en cifras de miles de millón', '4200', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de India? Responde en cifras de miles de millón', '3700', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Reino Unido? Responde en cifras de miles de millón', '3100', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Francia? Responde en cifras de miles de millón', '2900', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Italia? Responde en cifras de miles de millón', '2100', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Brasil? Responde en cifras de miles de millón', '2000', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Canadá? Responde en cifras de miles de millón', '1900', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Rusia? Responde en cifras de miles de millón', '1800', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Corea del Sur? Responde en cifras de miles de millón', '1700', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Australia? Responde en cifras de miles de millón', '1600', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de México? Responde en cifras de miles de millón', '1400', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de España? Responde en cifras de miles de millón', '1400', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Indonesia? Responde en cifras de miles de millón', '1300', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Países Bajos? Responde en cifras de miles de millón', '990', 'BEGINNER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Arabia Saudita? Responde en cifras de miles de millón', '880', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Turquía? Responde en cifras de miles de millón', '820', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Suiza? Responde en cifras de miles de millón', '800', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Polonia? Responde en cifras de miles de millón', '670', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Argentina? Responde en cifras de miles de millón', '620', 'TOURIST'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Suecia? Responde en cifras de miles de millón', '590', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bélgica? Responde en cifras de miles de millón', '580', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Tailandia? Responde en cifras de miles de millón', '570', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Irlanda? Responde en cifras de miles de millón', '530', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Noruega? Responde en cifras de miles de millón', '490', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Israel? Responde en cifras de miles de millón', '490', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Singapur? Responde en cifras de miles de millón', '470', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Austria? Responde en cifras de miles de millón', '470', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Nigeria? Responde en cifras de miles de millón', '440', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Emiratos Árabes Unidos? Responde en cifras de miles de millón', '440', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Vietnam? Responde en cifras de miles de millón', '430', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Malasia? Responde en cifras de miles de millón', '430', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Filipinas? Responde en cifras de miles de millón', '420', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Dinamarca? Responde en cifras de miles de millón', '400', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bangladés? Responde en cifras de miles de millón', '390', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Egipto? Responde en cifras de miles de millón', '380', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Sudáfrica? Responde en cifras de miles de millón', '380', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Colombia? Responde en cifras de miles de millón', '340', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Irán? Responde en cifras de miles de millón', '340', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Chile? Responde en cifras de miles de millón', '330', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Finlandia? Responde en cifras de miles de millón', '280', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Pakistán? Responde en cifras de miles de millón', '280', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Rumanía? Responde en cifras de miles de millón', '280', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de República Checa? Responde en cifras de miles de millón', '280', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Portugal? Responde en cifras de miles de millón', '250', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Irak? Responde en cifras de miles de millón', '250', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Perú? Responde en cifras de miles de millón', '240', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Grecia? Responde en cifras de miles de millón', '230', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Nueva Zelanda? Responde en cifras de miles de millón', '230', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Qatar? Responde en cifras de miles de millón', '220', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Argelia? Responde en cifras de miles de millón', '190', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Hungría? Responde en cifras de miles de millón', '180', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Kazajistán? Responde en cifras de miles de millón', '180', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Ucrania? Responde en cifras de miles de millón', '160', 'NOMAD'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Kuwait? Responde en cifras de miles de millón', '160', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Marruecos? Responde en cifras de miles de millón', '130', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Eslovaquia? Responde en cifras de miles de millón', '110', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Ecuador? Responde en cifras de miles de millón', '110', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Angola? Responde en cifras de miles de millón', '100', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Puerto Rico? Responde en cifras de miles de millón', '100', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Sri Lanka? Responde en cifras de miles de millón', '80', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Etiopía? Responde en cifras de miles de millón', '80', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de República Dominicana? Responde en cifras de miles de millón', '80', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Kenia? Responde en cifras de miles de millón', '70', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Birmania (Myanmar)? Responde en cifras de miles de millón', '70', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Guatemala? Responde en cifras de miles de millón', '70', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Omán? Responde en cifras de miles de millón', '70', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Ghana? Responde en cifras de miles de millón', '60', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bulgaria? Responde en cifras de miles de millón', '60', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Panamá? Responde en cifras de miles de millón', '60', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Costa Rica? Responde en cifras de miles de millón', '60', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Croacia? Responde en cifras de miles de millón', '60', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bielorrusia? Responde en cifras de miles de millón', '60', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Uruguay? Responde en cifras de miles de millón', '60', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Tanzania? Responde en cifras de miles de millón', '50', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Líbano? Responde en cifras de miles de millón', '50', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Lituania? Responde en cifras de miles de millón', '50', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Serbia? Responde en cifras de miles de millón', '50', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Eslovenia? Responde en cifras de miles de millón', '50', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Azerbaiyán? Responde en cifras de miles de millón', '50', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Turkmenistán? Responde en cifras de miles de millón', '50', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Uganda? Responde en cifras de miles de millón', '40', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Costa de Marfil? Responde en cifras de miles de millón', '40', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Jordania? Responde en cifras de miles de millón', '40', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bolivia? Responde en cifras de miles de millón', '40', 'silver'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Túnez? Responde en cifras de miles de millón', '40', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Camerún? Responde en cifras de miles de millón', '40', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Paraguay? Responde en cifras de miles de millón', '40', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bahrein? Responde en cifras de miles de millón', '40', 'CARTOGRAPHER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Letonia? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Zambia? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de El Salvador? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Camboya? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Senegal? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Islandia? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Honduras? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Chipre? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Papúa Nueva Guinea? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Trinidad y Tobago? Responde en cifras de miles de millón', '30', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Zimbabue? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Afganistán? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Nepal? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Laos? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bosnia y Herzegovina? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Botswana? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Mali? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Gabón? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Albania? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Mozambique? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Malta? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Burkina Faso? Responde en cifras de miles de millón', '20', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Nicaragua? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Mongolia? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Georgia? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Armenia? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Jamaica? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Namibia? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Mauritania? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Chad? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Madagascar? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Benín? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Ruanda? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Guinea? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Níger? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Moldavia? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Kosovo? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Tayikistán? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Haití? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Kirguistán? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Malawi? Responde en cifras de miles de millón', '10', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Fiyi? Responde en cifras de miles de millón', '5', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Montenegro? Responde en cifras de miles de millón', '5', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Surinam? Responde en cifras de miles de millón', '5', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Mauritania? Responde en cifras de miles de millón', '5', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Togo? Responde en cifras de miles de millón', '5', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Sierra Leona? Responde en cifras de miles de millón', '5', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Bután? Responde en cifras de miles de millón', '3', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Lesoto? Responde en cifras de miles de millón', '3', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Maldivas? Responde en cifras de miles de millón', '3', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Belice? Responde en cifras de miles de millón', '3', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Cabo Verde? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Gambia? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Guinea-Bisáu? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Burundi? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Liberia? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Timor Oriental? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Seychelles? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Antigua y Barbuda? Responde en cifras de miles de millón', '2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de San Vicente y las Granadinas? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Granada? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Comoras? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Dominica? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Samoa? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Santo Tomé y Príncipe? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Vanuatu? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de San Cristóbal y Nieves? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Islas Salomón? Responde en cifras de miles de millón', '1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Tonga? Responde en cifras de miles de millón', '0.5', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Micronesia? Responde en cifras de miles de millón', '0.4', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Kiribati? Responde en cifras de miles de millón', '0.2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Palaos? Responde en cifras de miles de millón', '0.2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Islas Marshall? Responde en cifras de miles de millón', '0.2', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Nauru? Responde en cifras de miles de millón', '0.1', 'CARTOGRAPH_MASTER'),
('economia', '¿Cuál es el Producto Interior Bruto (PIB) de Tuvalu? Responde en cifras de miles de millón', '0.06', 'CARTOGRAPH_MASTER');

INSERT INTO preguntas (category, description, answer, rank) VALUES
('renta', '¿Cuál es el PIB per cápita de Mónaco? (USD)', '234000', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Liechtenstein? (USD)', '184000', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Luxemburgo? (USD)', '135000', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Bermuda? (USD)', '122000', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Suiza? (USD)', '93800', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Irlanda? (USD)', '92500', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Noruega? (USD)', '89100', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Islas Caimán? (USD)', '88000', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Singapur? (USD)', '82800', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Estados Unidos? (USD)', '76300', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Islandia? (USD)', '74800', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Qatar? (USD)', '70700', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Dinamarca? (USD)', '68600', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Australia? (USD)', '65300', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Países Bajos? (USD)', '61800', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Suecia? (USD)', '58900', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Austria? (USD)', '55800', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Finlandia? (USD)', '53800', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Canadá? (USD)', '52700', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Alemania? (USD)', '51800', 'BEGINNER'),
('renta', '¿Cuál es el PIB per cápita de Bélgica? (USD)', '51200', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Israel? (USD)', '49800', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Reino Unido? (USD)', '48700', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Nueva Zelanda? (USD)', '47200', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Emiratos Árabes Unidos? (USD)', '46600', 'TOURIST'),
('economia', '¿Cuál es el PIB per cápita de Andorra? (USD)', '44900', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Francia? (USD)', '43900', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Japón? (USD)', '42100', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Italia? (USD)', '38900', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Corea del Sur? (USD)', '37300', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de España? (USD)', '34200', 'TOURIST'),
('renta', '¿Cuál es el PIB per cápita de Malta? (USD)', '33800', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Eslovenia? (USD)', '32800', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de República Checa? (USD)', '31500', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Portugal? (USD)', '29800', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Estonia? (USD)', '29400', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Arabia Saudita? (USD)', '27600', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Grecia? (USD)', '25800', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Eslovaquia? (USD)', '24100', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Lituania? (USD)', '23800', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Letonia? (USD)', '22600', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Polonia? (USD)', '21800', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Hungría? (USD)', '20900', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Croacia? (USD)', '19800', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Rumanía? (USD)', '18700', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Rusia? (USD)', '17900', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Chile? (USD)', '17300', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Argentina? (USD)', '16500', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Malasia? (USD)', '15600', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de México? (USD)', '14200', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de China? (USD)', '13500', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Turquía? (USD)', '12800', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Bulgaria? (USD)', '12300', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Costa Rica? (USD)', '11800', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Brasil? (USD)', '11200', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Colombia? (USD)', '10600', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Sudáfrica? (USD)', '9800', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Perú? (USD)', '9200', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Ecuador? (USD)', '8700', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Indonesia? (USD)', '8200', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de India? (USD)', '7600', 'NOMAD'),
('renta', '¿Cuál es el PIB per cápita de Filipinas? (USD)', '6900', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Vietnam? (USD)', '6300', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Nigeria? (USD)', '5700', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Pakistán? (USD)', '5100', 'CARTOGRAPHER'),
('renta', '¿Cuál es el PIB per cápita de Bangladesh? (USD)', '4500', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de Kenia? (USD)', '3900', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de Angola? (USD)', '3400', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de Tanzania? (USD)', '2900', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de Etiopía? (USD)', '2400', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de Afganistán? (USD)', '1900', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de República Democrática del Congo? (USD)', '1400', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de Burundi? (USD)', '900', 'silver'),
('renta', '¿Cuál es el PIB per cápita de Sudán del Sur? (USD)', '700', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de Somalia? (USD)', '600', 'CARTOGRAPH_MASTER'),
('renta', '¿Cuál es el PIB per cápita de República Centroafricana? (USD)', '500', 'CARTOGRAPH_MASTER');